### ISSUE TITLE
executing edist.py fails with a traceback under Python 3

### ISSUE THREAD

**Issue by stratakis** [JNRowe/upoints#3]
Tested with Python 3.5 and Python 3.6 on Fedora 25 and Fedora 26 machines respectively.

Invoking edist.py with Python 2 works as expected, although trying to do the same under Python 3 produces the following traceback:

Traceback (most recent call last):
  File "edist.py", line 25, in <module>
    sys.exit(edist.main())
  File "/home/<snip>/fedora-scm/python-upoints/upoints-0.12.2/upoints/edist.py", line 572, in main
    func = args._func
AttributeError: 'Namespace' object has no attribute '_func'

**Comment by JNRowe** [comment]
Thanks for reporting!  Serves me right for dipping in to the `_{internal}` namespace :/

I'm not convinced of the best fix right now, but plan to mull it over later today or tomorrow.  I have no plan to re-start development on `upoints`, so would prefer to find a sensible method that doesn't mean making too many *deep* changes.

**Comment by JNRowe** [comment]
To avoid spamming you with lots of email, I've created a new issue to track progress on support for newer Python versions.

While the referenced branch fixes the TB, I won't be pushing the hack to master.  None of the affected versions are listed as compatible in `setup.py`, so I'll wrap up some proper changes and cut a new release.
